### ISSUE TITLE
Error trying to run build result

### ISSUE THREAD

**Issue by Swedneck** [xdaimon/music_visualizer#3]
`main: /builddir/build/BUILD/glfw-3.2.1/src/window.c:774: glfwSetWindowUserPointer: Assertion 'window != NULL' failed.
[1]    15799 abort (core dumped)  ./main`

i followed the build instructions (although im on fedora 27) and copied the src/shaders/ directory to the same directory as the build result.

**Comment by xdaimon** [comment]
This is probably happening because the app is requesting a window with opengl version 4.3 and your machine not supporting that opengl version.

I can reduce the GL requirement to 3.3

**Comment by xdaimon** [comment]
Could you verify that the latest commit fixes the issue for you?

**Comment by Swedneck** [comment]
That fixed it!
