### ISSUE TITLE
What is the license for this code? 

### ISSUE THREAD

**Issue by cmaughan** [xdaimon/music_visualizer#5]

**Comment by xdaimon** [comment]
Any code that I wrote (shaders, ...) is under https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by xdaimon** [comment]
What did you have in mind?

**Comment by cmaughan** [comment]
I was looking at some of your C++ code.  My project is (or will be) MIT licensed, so I tend to stay away from stuff that isn't totally free.
